version: "3.1"
services:

  mongo:
    container_name: money-mongodb
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=money

  server:
    container_name: money-server
    image: ghcr.io/jakub-spiewak/money/server:latest
    ports:
      - "8002:8080"
    depends_on:
      - mongo
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"

  ui:
    container_name: money-ui
    image: ghcr.io/jakub-spiewak/money/ui:latest
    depends_on:
      - server
    ports:
      - "8001:80"
