spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: root
      database: money
      authentication-database: admin

springdoc:
  api-docs:
    resolve-schema-properties: true
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG