name: Build UI docker image

on:
  push:
    paths:
      - "ui/*"
    branches: [ master ]

jobs:
  ui-build-and-publish-docker-image:
    name: UI - Build and push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image to Github Packages
        uses: docker/build-push-action@v2
        with:
          context: ./ui
          file: ./ui/docker/Dockerfile
          tags: ghcr.io/jakub-spiewak/money/ui:latest
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}